/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantRouteRouteImport } from './routes/$tenant/route'
import { Route as New_datasetRouteImport } from './routes/new_dataset'
import { Route as TenantIndexRouteImport } from './routes/$tenant/index'
import { Route as TenantDatasetsRouteImport } from './routes/$tenant/datasets'
import { Route as TenantFacetsRouteImport } from './routes/$tenant/facets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRouteRoute = TenantRouteRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const New_datasetRoute = New_datasetRouteImport.update({
  id: '/new_dataset',
  path: '/new_dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantDatasetsRoute = TenantDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantFacetsRoute = TenantFacetsRouteImport.update({
  id: '/facets',
  path: '/facets',
  getParentRoute: () => TenantRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/new_dataset': typeof New_datasetRoute
  '/$tenant/datasets': typeof TenantDatasetsRoute
  '/$tenant/facets': typeof TenantFacetsRoute
  '/$tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new_dataset': typeof New_datasetRoute
  '/$tenant/datasets': typeof TenantDatasetsRoute
  '/$tenant/facets': typeof TenantFacetsRoute
  '/$tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/new_dataset': typeof New_datasetRoute
  '/$tenant/datasets': typeof TenantDatasetsRoute
  '/$tenant/facets': typeof TenantFacetsRoute
  '/$tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenant'
    | '/new_dataset'
    | '/$tenant/datasets'
    | '/$tenant/facets'
    | '/$tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/new_dataset' | '/$tenant/datasets' | '/$tenant/facets' | '/$tenant'
  id:
    | '__root__'
    | '/'
    | '/$tenant'
    | '/new_dataset'
    | '/$tenant/datasets'
    | '/$tenant/facets'
    | '/$tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantRouteRoute: typeof TenantRouteRouteWithChildren
  New_datasetRoute: typeof New_datasetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new_dataset': {
      id: '/new_dataset'
      path: '/new_dataset'
      fullPath: '/new_dataset'
      preLoaderRoute: typeof New_datasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/': {
      id: '/$tenant/'
      path: '/'
      fullPath: '/$tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/datasets': {
      id: '/$tenant/datasets'
      path: '/datasets'
      fullPath: '/$tenant/datasets'
      preLoaderRoute: typeof TenantDatasetsRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/facets': {
      id: '/$tenant/facets'
      path: '/facets'
      fullPath: '/$tenant/facets'
      preLoaderRoute: typeof TenantFacetsRouteImport
      parentRoute: typeof TenantRouteRoute
    }
  }
}

interface TenantRouteRouteChildren {
  TenantDatasetsRoute: typeof TenantDatasetsRoute
  TenantFacetsRoute: typeof TenantFacetsRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteRouteChildren: TenantRouteRouteChildren = {
  TenantDatasetsRoute: TenantDatasetsRoute,
  TenantFacetsRoute: TenantFacetsRoute,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteRouteWithChildren = TenantRouteRoute._addFileChildren(
  TenantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantRouteRoute: TenantRouteRouteWithChildren,
  New_datasetRoute: New_datasetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
